services:
  frontend:
    build:
      context: .
      target: web_server
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: irwks/borrowit-frontend:latest
    environment:
      FPM_HOST: backend
    restart: always
    volumes:
      - ./uploads:/app/public/uploads
    depends_on:
      - backend
    ports:
      - "${PUBLIC_PORT}:80"
    networks:
      - borrowit

  backend:
    build:
      context: .
      target: php_fpm
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: irwks/borrowit-backend:latest
    env_file: .env
    working_dir: /app
    restart: always
    volumes:
      - ./uploads:/app/public/uploads
    expose:
      - "9000"
    networks:
      - borrowit

  mysql:
      restart: unless-stopped
      image: mysql/mysql-server:8.0
      environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
          - mysql:/var/lib/mysql
      networks:
          - borrowit

networks:
  borrowit:
    driver: bridge

volumes:
    mysql:
        driver: local
