services:
  frontend:
    build:
      context: .
      target: web_server
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: irwks/borrowit-frontend:latest
    environment:
      FPM_HOST: backend
    restart: always
    volumes:
      - ./uploads:/public/uploads
    depends_on:
      - backend
    ports:
      - "${PUBLIC_PORT}:80"
    networks:
      - borrowit

  backend:
    build:
      context: .
      target: php_fpm
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: irwks/borrowit-backend:latest
    env_file: .env
    working_dir: /app
    restart: always
    volumes:
       - ./uploads:/public/uploads
    expose:
      - "9000"
    networks:
      - borrowit

networks:
  borrowit:
    driver: bridge
